language: ruby
rvm:
- 2.2.1
before_script:
- chmod +x ./script/cibuild
script: "./script/cibuild"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
notifications:
  on_success: always
  on_failure: always
  email: false
  slack:
    secure: J2+rqS3pt/l9GYIvImWiG5+b/WLYYN4uBPN8j9qY8wSz6XFoARwOOABf8B53Y7i9iGGKH6v95noClJETR+0OSgXjNNe377Xd4ZyXAMDf9BSd/tNLt6X7xnikbm8qB+BUYzVKsocDZFu7Wn+OL00nBk5ToKYY3f4D/cphN+SwHBt1J/IXj3H/zmvbD9zLW2wCvlpvj89tKTsLY9lLr+kpyU+Vodp9nCRBRlLCI3sAjnEtRMuGXVwJt6ZODYvjz7/nGpdPJkZM2nm3DqUvIihqwV0cnhC2qMoPe48ocTsq92lLK1cC7xmO0lPgHFMgReAgehMVAOa433BQCo3dNkB0aNO1fpdYLwrLrm4wnmRcwPEO/80nhMXUNtgMsHwfzmUUiwhnzAllmkGcLFznJUVzrXYw6kd7wxnccYKtrvo0UJZpAjo9JZxQEqs5sgVfBGOwxyWhtUOXlO9SMxri+mw1lO2xpI18XtsHki+yEcLQ+40UbwMMDINiAEXrGHGWq/nM2rlf+c4HQrrKAYSv+PQBz4lcL3uwGsKUntiFquwbzsdOYGYJ3+MGeOV+7VrWPMtS38JGJnFBsfxs/Z4qRvJ/8tvpbTRpHwWLQuBGHuWwJ8mPdPcCCIeD6SQdcMkzVR0GtwbZKyl0aN02eMDAXLztkIJbh1WlmZB+SoIjofN3MfM=
