# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           :year/:month/:day/:title/
relative_permalinks: true

# Setup
title:               Bit of A Byte
tagline:             "cat $(find /var/log -name '*.log' -print | head -n 3)"
description:         'My name is Natalie and I spend most of my time taking apart things I have no business taking apart.'
url:                 http://zyradyl.github.io
baseurl:             ''
paginate:            3

# About/contact
author:
  name:              Natalie M. Spencer
  url:               https://twitter.com/zyradyl
  email:             nmspencer89@gmail.com

# Source vars
version:             0.5.0
github:              "https://github.com/zyradyl"
repo:                "https://github.com/zyradyl/zyradyl.github.io"

# Page Listing
pages_list:
  About:             /about
  Archive:           /archive
  Tags:              /tags
  Feed:              /atom.xml
