# Permalinks
permalink:           :year/:month/:day/:title/

# Setup
title:               Bit of A Byte
tagline:             "cat $(find /var/log -name '*.log' -print | head -n 5)"
description:         'My name is Natalie and I spend most of my time taking apart things I have no business taking apart.'
url:                 http://zyradyl.github.io
baseurl:             ''

# About/contact
author:
  name:              Natalie M. Spencer
  url:               https://twitter.com/zyradyl
  email:             nmspencer89@gmail.com

# Optional features
#google_analytics_id: UA-XXXX-Y

# Source vars
version:             0.6.0
github:              "https://github.com/zyradyl"
repo:                "https://github.com/zyradyl/zyradyl.github.io"

# Plugins
plugins:            [jekyll-paginate]
paginate:           5
paginate_path:      "page:num"

# Page Listing
pages_list:
  About:             /about
  Archive:           /archive
  Tags:              /tags
  Feed:              /atom.xml
  Site Information:  /site
